---
# tasks file for docker-compose
- name: find docker-compose
  shell: "which docker-compose"
  ignore_errors: yes
  register: result

- name: check docker installation
  meta: end_host
  when: (result.rc == 0) and (force == 'false') 


- name: install docker-compose
  apt:
    name: docker-compose
    state: present 
  when: (result.rc == 1) or (force == 'true')

